server/RdtClient.Service/Models/QBittorrent/TorrentFileItem.cs
server/RdtClient.Service/Services/QBittorrent.cs
server/RdtClient.Web/Controllers/QBittorrentController.cs

It seems that recently sonarr and radarr have [changed the qbittorrent integration](https://github.com/Sonarr/Sonarr/commit/813f8869202b54048db8d792ee6c3f0d060dbd72#diff-4aa480003e8ce16bee777a84e906e71a29f45c4d6ea7c25bdbb2080795c36460R229) such that this endpoint is required for file mapping to work (and prevent a fatal error).
I've tested this api works with both sonarr and radarr.
Also thanks for creating this project!

Implement api/v2/torrents/files endpoint

---

server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs

Ran into a case when magnet.links returned empty .files. Retrying didnt help. Dunno how common this is, but checking for null here fixes it and it downloads just fine after that.

fix: alldebrid with empty .files

---

server/RdtClient.Web/Controllers/QBittorrentController.cs

- ### Problem
When using multiple *arr instances (sonarr, radarr ...), the queue
on each instance displays *all* torrents being processed by RDT.
The normal behaviour is to display torrents that have the same
category as the one set in the DownloadClient config on
radarr/sonarr.
*arr uses the `/api/v2/torrents/info` QBittorrent endpoint which
accepts a `category` query string.
This is how the Qbittorent API behaves when that query string
exists:
```text
See https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list
Get torrents with the given category.
empty string means "without category";
no "category" parameter means "any category"
```
See [here](https://github.com/Radarr/Radarr/blob/3125b038d5c2ca8c12f089059b7ca3303456aa9d/src/NzbDrone.Core/Download/Cl …

Filter torrents with the category query string:

---

Dockerfile

The `VOLUME` definition has some unwanted side-effects, for example always creating a volume as mentioned here: https://github.com/rogerfar/rdt-client/issues/422

Removed unwanted `VOLUME` as it has unintended side-effects

---

client/src/app/torrent-status.pipe.ts
client/src/app/torrent-table/torrent-table.component.html
server/RdtClient.Service/Services/QBittorrent.cs

Hi, I noticed that the qBitorrent API was missing a few features:
- Reporting the `progress` of the debris torrent download
- at the moment, the progress is always 0% until the torrent is downloaded in the debris
- after this pr, the progress reports the torrent download from 0% to 50% and the host download from 50% to 100%
- Marking downloads properly `stalled`
- after this pr, available seeders are reported properly
- after this pr, when the Debris status is `downloading torrent` but there are no seeders, it marks the torrent status as `stalled`
In this PR, I also fix some floating point inconsistencies by switching from `Single` to `Decimal`

qBittorrent API improvements

---

server/RdtClient.Service/Services/Downloaders/InternalDownloader.cs

This PR tires to fix https://github.com/rogerfar/rdt-client/issues/579. 
With this fix the download speed limit will be consider between all active downloads.
Negative effect of this PR:
Because this https://github.com/rogerfar/Downloader.NET does not change the download speed for already started chunks, it would result in potentially slower download speed than expected.

download limit now takes in to consideration total active downloads

---

server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

This changes the download url to retrieve individual files, rather than zip. This will fix the MethodNotAllowed error preventing downloads from starting due to TorBox backend change. It also includes a fix for source parameter null error.
This should close #618.

[TorBox] Fix MethodNotAllowed, source parameter null, preventing download of files 

---

client/src/app/setup/setup.component.html
server/RdtClient.Data/Data/DownloadData.cs
server/RdtClient.Data/Migrations/20241210071621_Downloads_Add_FileName.Designer.cs
server/RdtClient.Data/Migrations/20241210071621_Downloads_Add_FileName.cs
server/RdtClient.Data/Models/Data/Download.cs
server/RdtClient.Data/Models/Internal/DbSettings.cs
server/RdtClient.Service/Helpers/DownloadHelper.cs
server/RdtClient.Service/Services/Downloads.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/ITorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs
server/RdtClient.Service/Services/TorrentRunner.cs
server/RdtClient.Service/Services/Torrents.cs

This PR fixes the issue in #616 where filenames are being named to the download uuid. It does this by adding a new function to the TorrentClients to handle filenames from a downloadurl, which is saved in the db under each download item.
This has been tested with Internal, Aria2, and Bezzad. I tried testing with Symlink but the TorBox webdav was timing out for me. 
This will close #616.

Fix for TorBox incorrect filenames

---

server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

This is a fix for source parameter null log spam.
This is caused when a torrent is taking a while during metaDL, or when a torrent errors out, the value of files can/will be null, and if the `?? []` is removed it causes the log spam from #618.

[TB] Fix source parameter null log spam #618

---

server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs

Fixes #594 (specifically https://github.com/rogerfar/rdt-client/issues/594#issuecomment-2494975478).
Fixes #399 (again, see https://github.com/rogerfar/rdt-client/issues/399#issuecomment-2569935647).
Possibly fixes #648 (if I understood the issue correctly?).
This PR fixes 2 issues (both related to AllDebrid):
- Folder structure not being preserved.
- Include/exclude filters not working.
Both are fixed in the same PR because they depend on each other.
The first issue is fixed by reconstructing the path and using that as the file path, instead of only the filename.
The filters weren't implemented because a single link could have multiple files, as specified by this comment from 2021: https://github.com/rogerfar/rdt-client/issues/44#issuecomment-955615719
I've checked with multiple …

fix(AllDebrid): Implement regex filters & preserve folder structure

---

server/RdtClient.Service/Helpers/DownloadHelper.cs

Fixes #648.
You can't have multiple files at the root of a torrent. It's either a single file or a directory containing multiple files.
AllDebrid goes along with this and doesn't place torrents in a directory if it only contains a single file. RDT didn't handle this case.
This was fine, except for the people using AllDebrid with the rclone/symlink downloader. People using the other downloaders would've noticed that their files got placed into a directory with the same name as the file it contains, which shouldn't happen.
I've tested this with AllDebrid and the internal downloader using a single-file torrent and a multi-file torrent,
`<nyaa dot si>/view/1806288` and `<nyaa dot si>/view/1350495` respectively. The single-file torrent was placed in `/data/downloads/FILE.mkv`, and the files …

fix: Fix invalid download path with single-file torrents

---

Dockerfile

At the moment, `docker build` clones the master branch from this repo. - this makes it impossible to make a docker container with a different version from the current master branch without editing the Dockerfile.
This PR changes the Dockerfile to use the current local files on disk - so if you `git checkout` to a different commit, the resulting docker images will be different.

Use local files when building docker image

---

server/RdtClient.Data/Migrations/20250106112750_Torrent_Add_ClientKind.Designer.cs
server/RdtClient.Data/Migrations/20250106112750_Torrent_Add_ClientKind.cs
server/RdtClient.Data/Models/Data/Torrent.cs
server/RdtClient.Service/Helpers/DownloadHelper.cs
server/RdtClient.Service/Services/DownloadClient.cs
server/RdtClient.Service/Services/Downloaders/SymlinkDownloader.cs
server/RdtClient.Service/Services/QBittorrent.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

fix: Improve path fixes for Alldebrid & only apply them to Alldebrid

---

README.md
client/src/app/add-new-torrent/add-new-torrent.component.html
client/src/app/torrent-table/torrent-table.component.html
client/src/app/torrent/torrent.component.html
server/RdtClient.Data/Enums/DownloadClient.cs
server/RdtClient.Data/Models/Internal/DbSettings.cs
server/RdtClient.Service/Helpers/DownloadHelper.cs
server/RdtClient.Service/RdtClient.Service.csproj
server/RdtClient.Service/Services/DownloadClient.cs
server/RdtClient.Service/Services/Downloaders/DownloadStationDownloader.cs
server/RdtClient.Service/Services/TorrentRunner.cs
server/RdtClient.sln

Hey there,
I've added a new download client to the rdt-client: the Synology Download Station! It should now support managing downloads through Synology devices.
This feature has been tested with RealDebrid from early October until the recent RealDebrid update. Since then, I've tested it with AllDebrid, and it's working smoothly.
One thing I've noticed while working on this is that sometimes the application creates subfolders for downloads, but other times it doesn’t. Is this normal behavior? If not, could you clarify how it's supposed to work?
Looking forward to your feedback!

Add Synology Download Station Support

---

client/src/app/torrent-table/torrent-table.component.html

I often check rdt-client to know what I have downloaded, mostly because it keep me log-in and is very fast compared to all the **arr.
I want to be able to sort by request date so I made some change and here is my proposition :

Proposition : Add request date on table for sorting

---

server/RdtClient.Service/Helpers/DownloadHelper.cs
server/RdtClient.Service/Services/DownloadClient.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs

Hopefully fixes #671 
The changes to get AllDebrid+Symlink Downloader to work with all structures of torrents has caused other users issues.
Since the logic in `DownloadHelper` was changed (which is used for every Downloader), some users' files are ending up in the wrong place in `/data/downloads` (or wherever their downloads end up).
This PR reverts the changes to `DownloadHelper` and introduces a new variable in `DownloadClient.cs` - `symlinkSourcePath`. For every downloader other than `AD`, `symlinkSourcePath` is just `downloadPath` - exactly the same as v2.0.94. But for torrents with `TorrentClientKind.AllDebrid`, we use the static `AllDebridTorrentClient.GetSymlinkPath` to get the exact path to where we expect the file to show up in the user's rclone mount.
Ideally, this would be …

[Fix] Revert changes to `DownloadHelper`, move AD-symlink specific fixes to `AllDebridTorrentClient.GetSymlinkPath`

---

README.md

Fixes #686 
Not sure if the Username/Password bullet points are too verbose/repetitive

Update `readme` to include Synology Download Station. 

---

server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

Fixes #672  (I think - will know more when issue author replies) by adding logic to exclude files matching `ExcludeRegex`/not matching `IncludeRegex`/smaller than `DownloadMinSize`
`AD` and `RD` both use `IncludeRegex`, `ExcludeRegex` and `DownloadMinSize` to decide which files to download in `SelectFiles` and `GetDownloadLinks` respectively. `TB` and `PM` do not, so they won't listen to the include/exclude regex options.
This `SelectFiles`  behaviour seems to be unique to RD - that before the torrent has been downloaded, you can tell RD which files you want downloaded. Other debrid services will always download the entire torrent.
I think this part of the system (selecting files) could probably do with a refactor, maybe by changing `ITorrentClient#GetDownloadLinks` for something else, …

[PM] [TB] Fix: Implement `IncludeRegex`, `ExcludeRegex`, and `DownloadMinSize` 

---

server/RdtClient.Data/Data/ITorrentData.cs
server/RdtClient.Data/Data/TorrentData.cs
server/RdtClient.Data/DiConfig.cs
server/RdtClient.Service.Test/Helpers/DownloadHelperTest.cs
server/RdtClient.Service.Test/RdtClient.Service.Test.csproj
server/RdtClient.Service.Test/Services/Downloaders/DownloadStationDownloaderTest.cs
server/RdtClient.Service.Test/Services/TorrentClients/AllDebridTorrentClientTest.cs
server/RdtClient.Service.Test/Services/TorrentsTest.cs
server/RdtClient.Service/DiConfig.cs
server/RdtClient.Service/Helpers/DownloadHelper.cs
server/RdtClient.Service/Helpers/IDelayProvider.cs
server/RdtClient.Service/RdtClient.Service.csproj
server/RdtClient.Service/Services/Downloaders/DownloadStationDownloader.cs
server/RdtClient.Service/Services/Downloads.cs
server/RdtClient.Service/Services/IDownloads.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/Torrents.cs
server/RdtClient.Service/Wrappers/IProcess.cs
server/RdtClient.Service/Wrappers/IProcessFactory.cs
server/RdtClient.Service/Wrappers/Process.cs
server/RdtClient.Service/Wrappers/ProcessFactory.cs
server/RdtClient.sln

Writing this latest edit made me realise I want to do a little more work on this. It's ready for review, but imo not ready to merge
I've been working on adding unit tests.
Since this is the *introduction* of unit tests, **I'd like to ask any reviewers to be *really* nitpicky**. Other contributors may use these as templates for future unit tests, so it's important this pr exemplifies ideal tests. Stuff like names (`Mocks`, `Fake*`, the data used in tests, `MemberData` classes, etc), and patterns for the unit tests (asserting log lines, where the fake/fixture data comes from) are really important to get right now imo.
My minimal goals for this PR (figuring out the *how* of adding unit tests) is mostly completed. I think I've presented solutions for pretty much all of the dependency …

feat: Add unit tests

---

server/RdtClient.Service/Services/DownloadClient.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs

Fixes #713  (at least partially)
Not entirely sure why yet, but since AD silently updated how their `/v4.1/magnets/status` endpoint works when no `id` is specified (it no longer returns files), symlink path resolution for single file torrents is broken.
Turns out this is because we were always using the `downloadPath DownloadHelper.GetDownloadPath()` rather than the `AllDebridTorrentClient.GetSymlinkPath`, because `Type` was not set at that point.
I've reordered the code so `Type` is defined before it's used.
This fixes AD symlinks for single file torrents, while keeping functionality for both `DL` and `AD` for all the torrents that already worked.
I've tested with [`Torrents.zip`](https://github.com/user-attachments/files/18724545/Torrents.zip) on both `AD` and `DL`

Actually use `GetSymlinkPath` logic

---

server/RdtClient.Service.Test/Services/TorrentClients/AllDebridTorrentClientTest.cs
server/RdtClient.Service.Test/Services/TorrentsTest.cs

Per feedback in #691 uses `TheoryData<>` for better type safety in tests.

Use `TheoryData<>` instead of `Object[]` for theory data

---

server/RdtClient.Service/RdtClient.Service.csproj

Updates TorBox.NET to 1.5.0 to expose interfaces (https://github.com/asylumexp/TorBox.NET/pull/2)

[TB] Update TorBox.NET to 1.5.0

---

server/RdtClient.Service.Test/Services/DownloadableFileFilterTest.cs
server/RdtClient.Service.Test/Services/TorrentClients/AllDebridTorrentClientTest.cs
server/RdtClient.Service/DiConfig.cs
server/RdtClient.Service/Services/DownloadableFileFilter.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/DebridLinkTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs
server/RdtClient.Service/Services/Torrents.cs

I'm not a fan of DRY for DRY's sake, but I think this is a worthwhile abstraction.
Currently, every TorrentClient except `DebridLink` implements basically the same thing: a file filter which includes only files above `DownloadMinSize` (if nonzero) and either matching `IncludeRegex` (if present) or `ExcludeRegex` (if present and `IncludeRegex` not present).
AD and RD both currently ignore the filter if the filter would exclude all files. There seems to be some demand for this to be changed (https://github.com/rogerfar/rdt-client/issues/429#issuecomment-2433418245), so I'm willing to push a commit removing this on request (it's only a few lines). 
This PR also adds the filtering logic to `DL`, so all the `TorrentClients` will not only download fiels matching the filter.
I chose to listen to …

refactor!: DRY Download Filtering 

---

server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

TB are experiencing high load from clients which don't set their user agent.
I'm willing to wager that a reasonable chunk of those clients are `rdt-client`.
This PR sets a user-agent so TB can easily tell `rdt-client` apart from other clients.
I've also spoken to them about implementing something similar to AD's "status -live mode", so we could just fetch updates to the list of all torrents rather than getting every single one every single time.

feat:  [TB] Set user-agent

---

server/RdtClient.Service.Test/Services/TorrentClients/AllDebridTorrentClientTest.cs
server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs

Brings AD and RD behaviour in line with other `ITorrentClient`s. 
Instead of including all files when all are excluded, the torrent will be put in an error state like the other `ITorrentClient`s.
fixes #757

feat: [AD] [RD] don't download anything when all files excluded

---

server/RdtClient.Data/Models/Internal/DbSettings.cs

The only usage of `DbSettingsDownloadClient.ProxyServer` is in `Bezzad` according to my IDE
See also: [GitHub search](https://github.com/search?q=repo%3Arogerfar/rdt-client%20ProxyServer&type=code) for the string `ProxyServer`
Closes #578

fix: typo - proxyserver setting applies to bezzad not internal

---

server/RdtClient.Web/Controllers/AuthController.cs

fixes #743 
In [794eec8](https://github.com/rogerfar/rdt-client/commit/794eec8), the following lines were added to `SetupProvider`
```csharp
var user = await authentication.GetUser();
if (user != null)
{
return StatusCode(401);
}
```
But in the frontend, setting up the provider is done after creating the user account, so `user != null`

fix: require auth to setup provider

---

client/src/app/models/profile.model.ts
client/src/app/navbar/navbar.component.html
server/RdtClient.Data/Models/Internal/DbSettings.cs
server/RdtClient.Data/Models/Internal/Profile.cs
server/RdtClient.Service/BackgroundServices/UpdateChecker.cs
server/RdtClient.Service/Services/Torrents.cs

Closes #552 
Adds a setting (under General) `DisableUpdateNotifications` (default `false`). When true, we won't show update notifications to users.
I also added some stuff to check if there have been any GitHub Security Advisories published. This is done by checking the list of published security advisories in `rogerfar/rdt-client` against a list of known fixed GHSA IDs. I'm pretty sure these IDs  are immutable. I figured given we expect to have very few reported vulnerabilities, hard-coding them won't be too bad. There's no official standard for how the version numbers should be done, so parsing the vulnerable version number with a regex or string manipulation may not work.
This is only really relevant if we want to use GHSAs to report vulnerabilities to our users. So I can revert the …

feat: Allow ignoring update notifications (but notify anyway if GHSA found)

---

server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs

Currently the `ProviderUpdater` runs even when all torrents are finished.
Presumably if all torrents are finished on the debrid provider, we no longer care about updates to its status. 
We know it's either
-  not there
which could be useful information for the symlink downloader, but afaik isn't used as such
- the same as before
so we won't need to change anything in the database
In a working sonarr/radarr + rdt-client setup, no torrents should be left lying around on `Finished`. But in practice, this sometimes happens, especially if users have misconfigured. My personal motivation for this is for the container I use for testing which often has finished downloads sitting around, but I've periodically found my main instance with torrents left on `Finished` because sonarr/radarr has …

`ProviderUpdater`: don't run if all torrents finished and `AutoImport == false`

---

client/src/app/torrent-table/torrent-table.component.html
client/src/app/torrent-table/torrent-table.component.scss

Fixes #758
Long words in torrents' `rdName`s causes a very wide table and a horizontal scroll bar to appear.
By letting the torrent names bee broken across multiple lines, they can be basically any width, so don't cause the torrent table to exceed its container.
Before: 
After:

add `word-break: break-all` to torrent name `td`

---

README.md

First, thanks for the awesome utility!
Some feedback on getting the client running on Arch using rootless Podman.  Works OOB with normal paths on the host and following the tips from LinuxServer.io, but some funny errors working with paths available through a CIFS mount.  
Still having some bugs I'm working out, but thought to get  a PR going if you thought these notes would be helpful to others.  These issues seem like an edge case; let me know if you want issues created for these.

Rootless Podman and CIFS Connections

---

server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

Currently, even when `torrentClientTorrent` is not `null`, `TorBoxTorrentClient.UpdateData(torrent, torrentClientTorrent)` does not use the second argument and instead fetches from `TB`.
This results in `n + 1` calls to `/mylist` and up to `n + 1` calls to `/getqueued` every time `ProviderUpdater` runs (where `n` is the number of torrents in TB which have been added to `rdt-client` - that is, the number of torrents in `rdt-client` which haven't been deleted from TB).
`ITorrentClient.UpdateData` is used only by the private method `Torrents.UpdateTorrentClientData`. That method is only called with `torrentClientTorrent` in 2 places, both in `Torrents.UpdateRdData`, which is called only by `ProviderUpdater`.
So `torrentClientTorrent` is always null unless it's called because of a …

[TB] use `torrentClientTorrent` (if passed) instead of re-fetching in `UpdateData`

---

server/RdtClient.Data/Models/Internal/DbSettings.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs

Closes #727
As RD's main api hostname (`api.real-debrid.com`) is blocked by some(?) Turkish ISPs, letting users use alternative/unblocked hostnames (`api-1.real-debrid.com` etc.) allows them to still use `rdt-client` despite the block.

feat: add setting to change RD api hostname

---

server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/DebridLinkTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/ITorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs
server/RdtClient.Service/Services/Torrents.cs

In #741 RD and AD were brought in line with other providers and don't download anything when all files are excluded.
But for RD, the error message isn't great - `Missing Parameter` is all that is shown to the user. This is an error from RD's API complaining because we didn't specify any `fileId`s.
Initially, I just threw an error in `RealDebridTorrentClient.SelectFiles` when `fileIds.Length == 0`. But that felt wrong - it's not really exceptional behaviour, and only works because of how we catch errors when calling this function.
Instead, I've decided to return the number of files selected, and if none are selected, call `MarkAllFilesExcluded` to put the torrent into the same error state as all the other providers would.
The second solution feels more elegant to me, but I'll happily close …

fix: return number of files selected from `SelectFiles` so we can handle all files excluded for RD

---

server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs

Fixes #771
For context, the code below is the only place `GetDownloadLinks` is called
https://github.com/rogerfar/rdt-client/blob/a660a86bb4606541f53e1879962ca4f51171f0e0/server/RdtClient.Service/Services/Torrents.cs#L238-L257
By returning `null` from `PremiumizeTorrentClient.GetDownloadLinks` when all files have been excluded, we take the wrong path through the code above.
<details><summary>Log excerpt from after this PR</summary>
<p>
```
[13:34:29 DBG] Add file
[13:34:29 DBG] bytes System.Byte[]
[13:34:29 DBG] Updating torrent info from debrid provider
[13:34:29 DBG] Adding A0BF6E90BCF31DB5635CD9F2158B76955FB91A40 torrent file for torrent TestMultiple (mY-3fR2N421Q_tjDgcfRIw - finished 100%) (d54ef891-bd12-4b0b-82dd-2a876f0b1cfb)
[13:34:29 DBG] Method: GET, Path: /Api/Torrents
[13:34:29 …
```

fix: [PM] `GetDownloadLinks`: return empty list not null when all files excluded

---

server/RdtClient.Data/Models/Internal/DbSettings.cs
server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs

Fixes #782
Makes the TorBox zipped download behaviour introduced in #749 opt-in.

[TB] Make zipped downloads optional

---

server/RdtClient.Service/Services/TorrentRunner.cs
server/RdtClient.Service/Services/Torrents.cs

Potentially fix&ZeroWidthSpace;es #790 
As much as is feasible, fixes #793 
Fixes #797 
I introduced a few bugs with #763 
1. the `AutoDelete` functionality will delete queued torrents, since they won't be found on the provider (they won't have been added yet)
2. if adding the torrent to the provider fails, the error won't be caught, the torrent won't be retried, and no error will be shown to the user

Debrid Queue fixes (don't auto delete queued torrents, handle errors when dequeueing)

---

server/RdtClient.Service/Services/Torrents.cs

fixes #597
When auto-importing, we never set the `HostDownloadAction`. This (understandably) confused users, given it was a setting they could set.
[GitHub Code Search](https://github.com/search?q=repo%3Arogerfar%2Frdt-client%20Settings.Get.Provider.Default.HostDownloadAction&type=code) for `Settings.Get.Provider.Default.HostDownloadAction`

fix: Set `HostDownloadAction` when auto-importing torrents

---

.github/workflows/build-release.yaml

Fixes #786 
By `dotnet build`ing on `ubuntu-latest`, no `.exe` was included in the output. 
Luckily since GitHub actions are free[^1] for public repos, we can just build it on Windows instead.
[^1]: "GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners"  [source](https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#about-billing-for-github-actions), [standard runners list](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)
[Here](https://github.com/Cucumberrbob/rdt-client/releases/tag/v2.0.109)'s a release using this workflow. You can see …

build: build GitHub release .zip on windows not linux

---

.github/workflows/build-docker-image.yml
Dockerfile

The [`Release Docker Image`](https://github.com/rogerfar/rdt-client/actions/workflows/build-docker-image.yml) GitHub Action takes around 8 minutes to run now.
This is in large part because it uses QEMU to build the arm image in a VM.
Recently, GitHub [released](https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/) ARM runners in public preview. These are part of the "[standard runners](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories)" set, meaning they're completely free, no matter how much we use them (since this is a public repo).
Using these runners means we can run the image building in parallel, and …

use arm GitHub Actions runner to build arm docker image

---

.github/workflows/build-docker-image.yml

fixes #800 
I forgot to copy over the "patch version" step when doing #796 
this PR adds that step back and uses `context: .` (instead of the default: git context) when building the container.

fix: patch version before building docker container in github action

---

client/src/app/settings/settings.component.html
client/src/app/settings/settings.component.ts

Replaced the static help text displayed for magnet handler registration with contextual links.
- [CanIUse.com entry for navigator.registerProtocolHandler](https://caniuse.com/mdn-api_navigator_registerprotocolhandler)
- [MDN glossary on secure contexts](https://developer.mozilla.org/en-US/docs/Glossary/Secure_Context/)

Magnet handler registration contextual links
